#!/usr/bin/env python3
"""
My Villa — Social Published Ledger

Single source of truth for "this social content is already live", so that a
companion which was published (and whose source file got moved away or
regenerated by the self-healing sweep) is never re-shown in the panel nor
regenerated — and the panel can treat an X "duplicate content" rejection as
proof-of-published instead of a hard error that loops forever.

Keyed two ways so it survives both LLM rewrites and manual edits:
  - slug + channel   → journal companions: stable even if the text is rewritten
  - text fingerprint → reactive posts (no slug) + an exact-duplicate backstop

Storage: _system/history/social_published.json — runtime-local (history/ is
gitignored), the same scope as x_publish_log.json. Every publish path that
records here runs in the same runtime checkout, so the ledger is consistent
for the panel, the publishers and the self-healing sweep alike.

Best-effort by design: any read/write error degrades to "unknown" — it never
blocks a publish and never hides a legitimate draft on an IO hiccup.
"""

import hashlib
import json
import re
from datetime import datetime
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SYSTEM_DIR = SCRIPT_DIR.parent
LEDGER = SYSTEM_DIR / "history" / "social_published.json"

# mtime-keyed cache so the panel's per-render scan doesn't re-read+re-parse
# the file once per draft.
_cache = {"mtime": None, "data": None}


def _norm_channel(channel) -> str:
    c = (channel or "").strip().lower()
    if c.startswith("x") or c == "twitter":
        return "x"
    if c.startswith("ig") or c.startswith("insta"):
        return "ig"
    if c.startswith("reddit"):
        return "reddit"
    return c


def fingerprint(text) -> str:
    """Normalized hash of a post's text. Operates on the first 500 chars so
    the publish side (full text) and the panel side (body[:500]) agree for the
    short posts we deal with. Collapses whitespace and lowercases."""
    t = (text or "")[:500].lower()
    t = re.sub(r"\s+", " ", t).strip()
    if not t:
        return ""
    return hashlib.sha1(t.encode("utf-8")).hexdigest()


def _load() -> dict:
    """→ {'slugs': set[(channel, slug)], 'fps': set[(channel, fp)]}."""
    try:
        st = LEDGER.stat()
    except OSError:
        return {"slugs": set(), "fps": set()}
    if _cache["mtime"] == st.st_mtime and _cache["data"] is not None:
        return _cache["data"]
    try:
        raw = json.loads(LEDGER.read_text(encoding="utf-8"))
        entries = raw.get("entries", []) if isinstance(raw, dict) else []
    except (OSError, json.JSONDecodeError):
        return {"slugs": set(), "fps": set()}
    slugs, fps = set(), set()
    for e in entries:
        ch = _norm_channel(e.get("channel"))
        slug = (e.get("slug") or "").strip()
        fp = (e.get("fp") or "").strip()
        if slug:
            slugs.add((ch, slug))
        if fp:
            fps.add((ch, fp))
    data = {"slugs": slugs, "fps": fps}
    _cache["mtime"] = st.st_mtime
    _cache["data"] = data
    return data


def is_published(channel, text=None, slug=None) -> bool:
    """True if this content is already recorded as live on `channel`, matched
    by slug+channel (preferred — survives regeneration) or text fingerprint."""
    ch = _norm_channel(channel)
    idx = _load()
    if slug and (ch, str(slug).strip()) in idx["slugs"]:
        return True
    if text:
        fp = fingerprint(text)
        if fp and (ch, fp) in idx["fps"]:
            return True
    return False


def record(channel, text=None, slug=None, url="", note="") -> None:
    """Append a published entry. Duplicates are harmless (is_published dedups
    via sets). Best-effort: never raises."""
    ch = _norm_channel(channel)
    entry = {
        "channel": ch,
        "slug": (str(slug).strip() if slug else ""),
        "fp": fingerprint(text) if text else "",
        "url": url or "",
        "note": note or "",
        "at": datetime.now().isoformat(timespec="seconds"),
    }
    if not entry["slug"] and not entry["fp"]:
        return
    try:
        LEDGER.parent.mkdir(parents=True, exist_ok=True)
        try:
            raw = json.loads(LEDGER.read_text(encoding="utf-8"))
            if not isinstance(raw, dict) or "entries" not in raw:
                raw = {"entries": []}
        except (OSError, json.JSONDecodeError):
            raw = {"entries": []}
        raw["entries"].append(entry)
        LEDGER.write_text(json.dumps(raw, indent=2, ensure_ascii=False),
                          encoding="utf-8")
        _cache["mtime"] = None  # invalidate so the next read reflects the write
    except OSError:
        pass


# CLI: inspect / record / check the ledger by hand.
#   python3 social_ledger.py list
#   python3 social_ledger.py check x --slug some-slug
#   python3 social_ledger.py record x --slug some-slug --note "manual"
if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser(description="Social published ledger")
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("list")
    pc = sub.add_parser("check")
    pc.add_argument("channel")
    pc.add_argument("--slug")
    pc.add_argument("--text")
    pr = sub.add_parser("record")
    pr.add_argument("channel")
    pr.add_argument("--slug")
    pr.add_argument("--text")
    pr.add_argument("--url", default="")
    pr.add_argument("--note", default="manual")
    a = p.parse_args()
    if a.cmd == "list":
        try:
            print(LEDGER.read_text(encoding="utf-8"))
        except OSError:
            print("(ledger empty / not created yet)")
    elif a.cmd == "check":
        print(is_published(a.channel, text=a.text, slug=a.slug))
    elif a.cmd == "record":
        record(a.channel, text=a.text, slug=a.slug, url=a.url, note=a.note)
        print("recorded")
